= Avoid Hibernate N+1 Problem with Joins in Spring-Data/JPA
Jonathan Pearlin
2014-09-09
:jbake-type: post
:jbake-tags: spring, java
:jbake-status: published
:source-highlighter: prettify
:linkattrs:
:id: spring_data_hibernate_join
:icons: font
:hibernate: http://hibernate.org[Hibernate, window="_blank"]
:jpa: http://www.oracle.com/technetwork/java/javaee/tech/persistence-jsp-140049.html[JPA, window="_blank"]
:spring-data-jpa: http://projects.spring.io/spring-data-jpa/[Spring Data JPA, window="_blank"]

If you have used {hibernate} as your ORM for any length of time, you have inevitably run into the
http://docs.jboss.org/hibernate/orm/3.3/reference/en-US/html/performance.html#performance-fetching-custom[N+1 problem, window="_blank"].  This occurs when
{hibernate} queries an entity that has a collection of children entities that does not use a `JOIN` fetch mode to retrieve the children.  The simple solution
when using {hibernate} directly is to set the `FetchMode` to `JOIN`:

[source,java]
----
User user = (User) session.createCriteria(User.class)
                .setFetchMode("permissions", FetchMode.JOIN)
                .add( Restrictions.idEq(userId) )
                .uniqueResult();
----

However, if you are using {jpa} on top of {hibernate}, there is no way to set the `FetchMode` used by {hibernate} to `JOIN`.  In fact, {jpa} only
supports two types of fetching:  `EAGER` and `LAZY`.  Luckily, there is another {jpa} API that can be used to address this problem:  {spring-data-jpa}.  The
{spring-data-jpa} library provides a http://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl/[Domain Driven Design Specifications, window="_blank"]
API that allows you to control the behavior of the generated query.  This will allow you to tweak things such as the fetch mode to ensure the proper instruction
is passed to {hibernate} to address the N+1 problem.  I'm not going to go into a bunch of details on how to use the `JpaSpecificationExecutor`, as the {spring-data-jpa}
documentation does a pretty good job of covering it.  What is more important is how to control the fetch mode using it:

[source,java]
----
final long userId = 1;

final Specification<User> spec = new Specification<User>() {
    @Override
    public Predicate toPredicate(final Root<User> root, final CriteriaQuery<?> query, final CriteriaBuilder cb) {
        query.distinct(true);
        root.fetch("permissions", JoinType.LEFT);
        return cb.equal(root.get("id"), userId);
     }
};

List<User> users = userRepository.findAll(spec);
----

There are two important pieces of the example above.  The first is the setting of the `distinct` flag on the query to ensure that the proper (unique) results are returned as
a result of the join.  The second is the addition of a `fetch` hint to the root entity, telling the specification to perform a left join of the root to the entity mapped
by the "permissions" field of the root entity.  This ensures that {hibernate} will now perform a join instead of N+1 queries to fetch the root entity and its associated
children.