= Remote debugging a Spring Boot application launched by the Gradle plugin
Jonathan Pearlin
2014-07-15
:jbake-type: post
:jbake-tags: spring,gradle
:jbake-status: published
:source-highlighter: prettify
:linkattrs:
:id: spring_boot_remote_debug
:icons: font
:gradle: http://gradle.org[Gradle, window="_blank"]
:spring_boot: http://projects.spring.io/spring-boot/[Spring Boot, window="_blank"]

It is very helpful to be able to set break points in your IDE and attach to a running application to debug what is going on.  Java provides this functionality via
the http://docs.oracle.com/javase/7/docs/technotes/guides/jpda/conninv.html[JPDA Transport, window="_blank"].  Additionally, because the http://docs.spring.io/spring-boot/docs/1.1.1.RELEASE/reference/html/build-tool-plugins-gradle-plugin.html[Spring Boot Gradle Plugin, window="_blank"]
is built on top of the existing http://www.gradle.org/docs/current/userguide/application_plugin.html[Gradle Application Plugin, window="_run"], it is easy to provide JVM
arguments to the {spring_boot} application launcher from your {gradle} build script:

[source,groovy]
----
run {
    jvmArgs = ['-Xdebug', '-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=y']
}
----

When running the {spring_boot} application from {gradle}, the application will wait on start up until a remote debugger (such as from your IDE) connects to the
process on port 4000 via the JPDA Transport protocol:

[source]
----
root@laptop-mbp:~/sample_app$ ./gradlew run
:compileJava
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes
:findMainClass
:run
Listening for transport dt_socket at address: 4000
----

Once the debugger is attached, execution will continue on normally, halting only when it comes across any break points set in the debugger.