= Updating to the latest Docker/Boot2Docker version
Jonathan Pearlin
2014-08-05
:jbake-type: post
:jbake-tags: docker,boot2docker
:jbake-status: published
:source-highlighter: prettify
:linkattrs:
:id: docker_upgrade
:icons: font
:boot2docker: https://github.com/boot2docker/boot2docker[Boot2Docker, window="_blank"]
:docker: http://www.docker.com/[Docker, window="_blank"]
:homebrew: http://brew.sh/[Homebrew, window="_blank"]
:virtual_box: https://www.virtualbox.org/[Virtual Box, window="_blank"]

Not too long ago, the {docker} project released 1.0 release, which among many improvements includes a new default port for {docker}.  To update from {docker}
 < 1.0 to {docker} >= 1.0, you may run into issues as the port that {docker} listens on by default has changed from 4243 to 2375.  While things
may appear to start correctly after an upgrade, you may see the following error when attempting to run any {docker} client command:

[source]
----
$ boot2docker up

Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
----

This is because your {virtual_box} "boot2docker-vm" image is still listening on the old port and therefore is not receiving the forwarded commands.  You can verify this by
starting up {boot2docker} and ssh'ing (`boot2docker ssh`) into the VM to check the port that docker is listening on:

[source]
----
docker@boot2docker:~$ sudo netstat -ntpl | grep docker
tcp        0      0 :::4243                :::*                    LISTEN      627/docker
----

To fix this, use the following steps:

. Update to latest {boot2docker} and {docker} via {homebrew} (installing {boot2docker} will automatically install/update {docker} to the corresponding version).
. Run `boot2docker delete`.
. Delete the existing `~/.boot2docker` directory.
. Run `boot2docker init`
. Open {virtual_box}, select the `boot2docker-vm` and click on the "Settings" button.
.. Click on the "Network button" in the settings window, expand the "Advanced" area and click on the "Port Forwarding" button.  Verify that 2375 and 2022 are in the list.
. Run `boot2docker up`
. Run `boot2docker ssh`
. In the VM, run the following command to verify that {docker} is listening on port 2375:

[source]
----
sudo netstat -ntpl | grep docker

docker@boot2docker:~$ sudo netstat -ntpl | grep docker
tcp        0      0 :::2375                 :::*                    LISTEN      627/docker
----

You should now be able to connect to {docker} and use the command line client and the REST API!