[versions]
asciidoctorj = "2.5.13"
commons-io = "2.21.0"
freemarker = "2.3.34"
jbake = "2.6.7"
jetty = "12.1.4"
jffi = "1.3.14"
jna = "5.18.1"
jnr-constants = "0.10.4"
jnr-posix = "3.1.21"
jruby = "10.0.2.0"
pegdown = "1.6.0"

[libraries]

[bundles]


[plugins]
git-publish = { id = "org.ajoberstar.git-publish", version = "5.1.3" }
gretty = { id = "org.gretty", version = "4.1.10" }
jbake-site =  { id = "org.jbake.site", version = "5.5.0" }